VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "elao/symfony-standard-debian"
  config.vm.provision "shell", path: "./bootstrap.sh", privileged: true
end
